export function downloadScanHTML(items, scanType = null) {
  if (!items || items.length === 0) {
    alert("No scan data to download");
    return;
  }

  // 🔍 Detect scan type - use provided scanType or auto-detect
  let detectedType = scanType;
  if (!detectedType) {
    // Auto-detect: Check for Zigbee fields first, then Bluetooth
    if (items[0]["IEEE Address"] || items[0]["PAN ID"] || items[0]["LQI"]) {
      detectedType = "zigbee";
    } else if (items[0]["Device Name"] && items[0]["Device ID"]) {
      detectedType = "ble";
    } else {
      detectedType = "wifi";
    }
  }

  const isBluetooth = detectedType === "ble";
  const isZigbee = detectedType === "zigbee";
  const isWifi = detectedType === "wifi";

  // ---------------- ROWS ----------------
  const rows = items
    .map((it, i) => {
      if (isBluetooth) {
        return `
          <tr>
            <td>${i + 1}</td>
            <td>${it["Device Name"] || ""}</td>
            <td>${it["Device ID"] || ""}</td>
            <td>${it["Proximity (%)"] || ""}</td>
            <td>${it["Device Category"] || ""}</td>
            <td>${it["Advertised Stability"] || ""}</td>
            <td>${it["Pairing Required"] || ""}</td>
          </tr>
        `;
      }

      if (isZigbee) {
        return `
          <tr>
            <td>${i + 1}</td>
            <td>${it["Name"] || it["Device Name"] || ""}</td>
            <td>${it["IEEE Address"] || ""}</td>
            <td>${it["Network Address"] || ""}</td>
            <td>${it["RSSI"] || it["Signal (dBm)"] || ""}</td>
            <td>${it["LQI"] || ""}</td>
            <td>${it["Distance"] || ""}</td>
            <td>${it["PAN ID"] || ""}</td>
            <td>${it["Channel"] || ""}</td>
            <td>${it["Device Type"] || ""}</td>
            <td>${it["Security"] || it["Security Type"] || ""}</td>
            <td>${it["Battery Level"] || ""}</td>
          </tr>
        `;
      }

      // Wi-Fi
      return `
        <tr>
          <td>${i + 1}</td>
          <td>${it.Name || it.ssid || ""}</td>
          <td>${it.BSSID || ""}</td>
          <td>${it["Signal (dBm)"] || ""}</td>
          <td>${it["Signal (%)"] || ""}</td>
          <td>${it.Channel || ""}</td>
          <td>${it.Distance || ""}</td>
          <td>${it["Security Type"] || ""}</td>
        </tr>
      `;
    })
    .join("");

  // ---------------- HEADERS ----------------
  let tableHeaders;
  if (isBluetooth) {
    tableHeaders = `
      <th>#</th>
      <th>Device Name</th>
      <th>Device ID</th>
      <th>Proximity</th>
      <th>Category</th>
      <th>Stability</th>
      <th>Pairing</th>
    `;
  } else if (isZigbee) {
    tableHeaders = `
      <th>#</th>
      <th>Device Name</th>
      <th>IEEE Address</th>
      <th>Network Addr</th>
      <th>RSSI</th>
      <th>LQI</th>
      <th>Distance</th>
      <th>PAN ID</th>
      <th>Channel</th>
      <th>Device Type</th>
      <th>Security</th>
      <th>Battery</th>
    `;
  } else {
    tableHeaders = `
      <th>#</th>
      <th>SSID</th>
      <th>BSSID</th>
      <th>Signal (dBm)</th>
      <th>Signal %</th>
      <th>Channel</th>
      <th>Distance</th>
      <th>Security</th>
    `;
  }

  // ---------------- HTML ----------------
  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Signal Analyzer Report</title>
<style>
  body {
    font-family: Inter, Arial, sans-serif;
    margin: 30px;
    color: #111;
  }
  h1 {
    font-size: 22px;
  }
  .meta {
    color: #555;
    margin-bottom: 16px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 16px;
  }
  th, td {
    border-bottom: 1px solid #ddd;
    padding: 8px 10px;
    font-size: 13px;
    text-align: left;
  }
  th {
    background: #f3f5f9;
    font-weight: 600;
  }
  tr:hover {
    background: #f9fafb;
  }
  .footer {
    margin-top: 30px;
    font-size: 12px;
    color: #777;
  }
</style>
</head>

<body>
  <h1>📡 Signal Analyzer – ${isBluetooth ? "Bluetooth Scan Report" : isZigbee ? "Zigbee Scan Report" : "Wi-Fi Scan Report"}</h1>

  <div class="meta">
    Generated at: ${new Date().toLocaleString()} <br/>
    Total ${isBluetooth || isZigbee ? "devices" : "networks"}: ${items.length}
  </div>

  <table>
    <thead>
      <tr>
        ${tableHeaders}
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>

  <div class="footer">
    Generated by Signal Analyzer
  </div>
</body>
</html>
`;

  // ---------------- DOWNLOAD ----------------
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  const filename = isBluetooth ? "bluetooth" : isZigbee ? "zigbee" : "wifi";
  a.download = `${filename}-scan-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();

  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
